#! /usr/bin/python
# -*- coding=utf-8 -*-

from SimpleDocbookEditor.main import SimpleDocbookEditor
from SimpleDocbookEditor.informations import *
import gettext

gettext.install(UNIX_APPNAME, "/usr/share/locale")

if __name__ == "__main__":
    SimpleDocbookEditor().run()
